apiVersion: v1
kind: Pod
metadata:
  namespace: operate
  name: hello
spec:
  containers:
  - name: hello-1
    image: 192.168.33.9:5000/k8s/app/hellojenkins:1.0
    imagePullPolicy: IfNotPresent
    resources:
      requests:
        cpu: "1000m"
        memory: "1Gi"
    