pipeline {
	agent any
	stages {
		
		stage('Build') {
			steps {
				sh "========docker build============"
				sh 'docker build -t 192.168.33.9:5000/k8s/app/hellojenkins:1.0 .'
			}
		}
		
		stage('Push') {
			steps {
				echo "=============docker push============"
				sh "docker push 192.168.33.9:5000/k8s/app/hellojenkins:1.0"
				
			}
		}
	}
}
